### ISSUE TITLE
Sedikit masalah pada script contoh nested_loop.py

### ISSUE THREAD

**Issue by blissjaspis** [purwanto1337/belajarPython#2]
Hallo,
saya lagi baru memulai python dan setelah saya coba script dibawah error dikarenakan kurang buka tutup kurung.
https://github.com/purwanto1337/Belajarpython/blob/bdd3e7204bca3a38462c5c7b8e2cc6c4937a0631/python_dasar/nested_loop.py#L9

seharusnya `if (j > i/j) : print (i, " is prime")`

dan juga ada sedikit yang typo pada 
https://github.com/purwanto1337/Belajarpython/blob/bdd3e7204bca3a38462c5c7b8e2cc6c4937a0631/python_dasar/nilai_dalam_string.py#L3

seharusnya `print ("message[1:4]: ", messange[1:4])`
karena bila di jalankan `print ("message[1:4]: ", messange[1:3])` maka akan mengeluarkan output **oh** sedangkan pada contoh saya baca mengeluarkan output **ohn**

ty.

**Comment by purwnt** [comment]
@blissjaspis Terimakasih atas banyak kontribusinya.
Untuk nested loop yang seharusnya `if (j > i/j) : print (i, " is prime")` sekarang sudah diperbaiki, dan untuk typo `print ("message[1:4]: ", message[1:4])` pada manipulasi string juga sudah diperbaiki.
